# Enable Prometheus components
prometheus:
  enabled: true
  service:
    type: LoadBalancer
    annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  persistence:
    enabled: false
  

# Alertmanager settings
alertmanager:
  enabled: true
  service:
    type: ClusterIP
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "default"
      group_by: ["alertname", "severity"]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
    receivers:
      - name: "default"
        email_configs:
          - to: "markibaevadilet2@gmail.com"
            from: "alertmanager@gmail.com"
            auth_username: "user"
            auth_password: "password"

# Grafana settings
grafana:
  enabled: true
  service:
    type: LoadBalancer
  adminPassword: "admin123"
  persistence:
    enabled: false

# Enable Node Exporter
prometheus-node-exporter:
  enabled: true

# Enable Kube State Metrics
kube-state-metrics:
  enabled: true
